name: notifications_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  awesome_notifications: ^0.7.4+1
  fluttertoast: ^8.2.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

